import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, In, DeepPartial } from 'typeorm';
import { Season } from '~/entities/season.entity';

type QuarterName = 'Fall' | 'Winter' | 'Spring' | 'Summer';

interface AcademicSeasonInput {
  name: string;
  start_date: string;
  end_date: string;
}

@Injectable()
export class SeasonGenService {
  private readonly logger = new Logger(SeasonGenService.name);

  constructor(
    @InjectRepository(Season)
    private readonly seasonRepository: Repository<Season>,
  ) {}

  async generateSeasonsForYear(
    academicYear: number,
    fallStartDate?: string,
  ): Promise<Season[]> {
    const seasons = this.buildSeasonsForYear(academicYear, fallStartDate);

    const existing = await this.seasonRepository.find({
      where: { name: In(seasons.map((s) => s.name)) },
    });

    const existingByName = new Map(existing.map((season) => [season.name, season]));

    const generatedSeasons: DeepPartial<Season>[] = seasons.flatMap((season) => {
      const existingSeason = existingByName.get(season.name);
      const isAutoGenerated = existingSeason?.is_auto_generated ?? true;

      if (existingSeason && !isAutoGenerated) {
        this.logger.log(`Skipping manual season update: ${season.name}`);
        return [];
      }

      return [
        {
          ...season,
          id: existingSeason?.id,
          is_auto_generated: true,
        },
      ];
    });

    const saved = await this.seasonRepository.save(generatedSeasons as DeepPartial<Season>[]);

    this.logger.log(`Generated ${saved.length} seasons for academic year ${academicYear}`);
    return saved;
  }

  buildSeasonsForYear(
    academicYear: number,
    fallStartDate?: string,
  ): AcademicSeasonInput[] {
    const fallStart =
      fallStartDate != null
        ? this.alignToMonday(new Date(fallStartDate))
        : this.getFallStartDate(academicYear);

    const quarterConfigs: Array<{
      name: QuarterName;
      startDate: Date;
      seasonYear: number;
    }> = [
      {
        name: 'Fall',
        startDate: fallStart,
        seasonYear: academicYear,
      },
      {
        name: 'Winter',
        startDate: this.getWinterStartDate(academicYear + 1),
        seasonYear: academicYear + 1,
      },
      {
        name: 'Spring',
        startDate: this.getSpringStartDate(academicYear + 1),
        seasonYear: academicYear + 1,
      },
      {
        name: 'Summer',
        startDate: this.getSummerStartDate(academicYear + 1),
        seasonYear: academicYear + 1,
      },
    ];

    return quarterConfigs.map(({ name, startDate, seasonYear }, index) => {
      const nextStart = quarterConfigs[index + 1]?.startDate;
      const endDate = nextStart
        ? this.addDays(nextStart, -1)
        : this.addDays(this.getFallStartDate(academicYear + 1), -1);

      return {
        name: `${name} ${seasonYear}`,
        start_date: this.formatDate(startDate),
        end_date: this.formatDate(endDate),
      };
    });
  }

  public getFallStartDate(academicYear: number): Date {
    const candidate = new Date(Date.UTC(academicYear, 8, 24));
    return this.alignToPreviousMonday(candidate);
  }

  public getWinterStartDate(year: number): Date {
    const candidate = new Date(Date.UTC(year, 0, 2));
    return this.alignToMonday(candidate);
  }

  public getSpringStartDate(year: number): Date {
    const lastMonday = this.getLastMondayInMonth(year, 2);
    if (lastMonday.getUTCDate() === 31) {
      return this.addDays(lastMonday, 7);
    }
    return lastMonday;
  }

  public getSummerStartDate(year: number): Date {
    const firstMonday = this.getNthMondayInMonth(year, 5, 1);
    return this.addDays(firstMonday, 21);
  }

  private getLastMondayInMonth(year: number, month: number): Date {
    const lastDay = new Date(Date.UTC(year, month + 1, 0));
    return this.alignToPreviousMonday(lastDay);
  }

  private getNthMondayInMonth(year: number, month: number, n: number): Date {
    const firstOfMonth = new Date(Date.UTC(year, month, 1));
    return this.addDays(this.alignToMonday(firstOfMonth), 7 * (n - 1));
  }

  private alignToMonday(date: Date): Date {
    const result = new Date(date);
    const day = result.getUTCDay();
    if (day === 1) return result;
    const delta = (8 - day) % 7;
    result.setUTCDate(result.getUTCDate() + delta);
    return result;
  }

  private alignToPreviousMonday(date: Date): Date {
    const result = new Date(date);
    const day = result.getUTCDay();
    if (day === 1) return result;
    const delta = (day + 6) % 7;
    result.setUTCDate(result.getUTCDate() - delta);
    return result;
  }

  private alignToSunday(date: Date): Date {
    const result = new Date(date);
    const day = result.getUTCDay();
    const delta = (7 - day) % 7;
    result.setUTCDate(result.getUTCDate() + delta);
    return result;
  }

  private addDays(date: Date, days: number): Date {
    const result = new Date(date);
    result.setUTCDate(result.getUTCDate() + days);
    return result;
  }

  private formatDate(date: Date): string {
    return date.toISOString().slice(0, 10);
  }
}